# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

enable-beta-ecosystems: true

#registries:
#  github-antonycc:
#    type: maven-repository
#    url: https://maven.pkg.github.com/antonycc/ondemand-neo4j
#    username: x-access-token
#    password: ${{ secrets.GITHUB_TOKEN }}

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      # UTC
      time: "01:30"

  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      # UTC
      time: "01:45"

  # Maintain dependencies for GitHub Maven (via Gradle)
#  - package-ecosystem: "maven"
#    directory: "/maven-repository/github-antonycc"
#    schedule:
#      interval: "daily"
#      # UTC
#      time: "01:45"
      
  # Maintain dependencies for Maven (via Gradle)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      # UTC
      time: "02:00"
            

