name: Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Publish package
      uses: gradle/gradle-build-action@cd579d970f8aec1cf0cae5f62a8e418768970015
      with:
        arguments: publish bootBuildImage --info
        # --publishImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
